### ISSUE TITLE
Urns are being counted as enemies

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#10]
Relevant code:
getEnemiesForAltitude2 in Underworld.ts
budget in Unit.ts

Expected:
Urns should not count against the level unit spawn budget or unit types chosen

**Comment by jdoleary** [comment]
Reported by Skillo

**Comment by SoulMuncher** [comment]
As far as I can tell, urns are not actually being selected as one of the spawnable unit types in getEnemiesForAltitude2(), and are filtered out due to spawn probability 0. They are spawned later on in the Underworld's generateRandomLevelData() function, right before minibosses are selected.

However, I did notice that it's possible to find an urn miniboss since their id gets pushed to the unit list. How would you feel about adding a "minibossable" boolean to spawn params so that we can specifically filter out certain units for miniboss selection? Alternatively, miniboss creation could happen in the same place as enemy spawns and budgeting?
