### ISSUE TITLE
Adjust unit max mana

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#162]
I.E. Priest

Consider Mana Burn and Mana Steal

Do we want minibosses to have the same exact mana/regen as non minibosses?

**Comment by jdoleary** [comment]
I feel like minibosses should have increased mana max and regen so that they're harder to disable with mana burn and mana steal.

I feel like the way to determine how much max mana enemies should have is relative to both how much can be stolen and how often we want them to cast.  So if we want priests to be able to cast 2 turns back to back and then rest 1 turn, we can give them 2x mana, 1x regen, and 1x mana cost.  Then `x` should be relative to how much is sensible for a priest to have given how much you can burn.  I feel like burn and steal should definitely have a meaningful impact on a basic enemy like priest, so maybe it takes most of or all of their mana.  Right now mana burn takes 30 and mana steal takes 60.  So maybe priests have 60.  So in the formula above x = 30 so they have 60 max mana, 30 regen, 30 cost to cast.
This is just for example, but I think their mana should be structured something like that.

**Comment by SoulMuncher** [comment]
> I feel like minibosses should have increased mana max and regen so that they're harder to disable with mana burn and mana steal.

Sweet! I was thinking the same thing.

> ... I think their mana should be structured something like that.

Yeah that seems good 👍

**Comment by jdoleary** [comment]
We also have to consider if priests and summoners are still able to cast after being split.  It wouldn't make much sense for them to just become uncastable after 1 split

**Comment by SoulMuncher** [comment]
Yes. 

I'm also kind've thinking about it this way: A priest or summoner's ability is a lot more powerful than a glop's ability. They're also higher budget units and seem more reliant on mana thematically, so they might generally have higher max/regen/cost than glops. Against an enemy that is attuned with magic, Mana Burn/Steal would have both a smaller impact per cast (not take all of their mana), and higher potential overall (lots of mana to drain + potential damage). It also means that you can't make an ally summoner summon every turn by sending them 20 mana. I think all of that just makes sense intuitively and it's more or less set up this way right now.

I also want to look at their budget, health, etc. It's important that a green glop is harder than a blue glop, so the mana stats will shift a little based on that. It's important that mana burn is competitive with slash when it comes to killing mana based enemies and stuff like that.

Will make a PR soon

**Comment by SoulMuncher** [comment]
@jdoleary 

Should we consider player mana costs when doing this? Such as the cost of the resurrect ability?
The advantage would be having enemies use the same spells and world consistency but I'm kind've leaning away from it in favor of having separately controlled enemy balance. Might also be easier to maintain that way

**Comment by jdoleary** [comment]
> @jdoleary
> 
> Should we consider player mana costs when doing this? Such as the cost of the resurrect ability? The advantage would be having enemies use the same spells and world consistency but I'm kind've leaning away from it in favor of having separately controlled enemy balance. Might also be easier to maintain that way

I don't think we should.  Player spells are balanced to the player's capacity as a high volume caster.  This is the same thing I did earlier when priests had a ridiculous 160 mana.  I agree with your previous thought.  enemy mana max and regen need to be balanced according to their interaction with mana burn, mana steal, split and send mana.
