### ISSUE TITLE
Huge displace stack predicted wrong end location in multiplayer

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#177]

**Comment by SoulMuncher** [comment]
I wonder if this is related to #181

**Comment by jdoleary** [comment]
I attempted to reproduce this on both single and multi and could not

**Comment by SoulMuncher** [comment]
I've been able to repro this pretty consistently. Seems related to 181, but it's actually happening in Singleplayer as well, so maybe I was wrong about the root cause of the issue. The effect is still the same: When you add/remove a spell right before casting, it doesn't register, and it is cast without that change. I have some recordings of this but they are longer. I sent one on discord

- Queue up a few displace
- Take note of the last and second to last displace destination
- Add or Remove one displace using hotkeys, and then cast the spell immediately after
- Notice that the added/removed spell does not take effect, and you land somewhere other than what the prediction showed with that spell taken into consideration.

**Comment by jdoleary** [comment]
I am unable to reproduce this given your instructions

**Comment by SoulMuncher** [comment]
This was the repro I sent on 12/17, moving it here for context. Maybe it's been fixed since then @jdoleary 

https://github.com/jdoleary/Spellmasons/assets/68413161/a9be18db-9da9-4f01-9bab-cf9021efb626

**Comment by jdoleary** [comment]
Thank you for the context, this might have to do with
`        const cardIds = CardUI.getSelectedCardIds();`
using a DOM selector so if there's some kind of race condition with the dom updating it might not get the latest.

**Comment by jdoleary** [comment]
Was able to reproduce weird behavior consistently by making sure I changed the last spell a quick moment AFTER clicking. Between when the cast animation started and when it triggers

**Comment by jdoleary** [comment]
Is this still reproducible @SoulMuncher ?

**Comment by SoulMuncher** [comment]
> Is this still reproducible @SoulMuncher ?

Surprisingly no. Just tested it.

**Comment by jdoleary** [comment]
Boom!  Fixed by entropy!  My favorite
