### ISSUE TITLE
Resurrect doesn't set endedTurn to false

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#243]
You can also end turn before they get a chance to cast, after resurrecting them.

**Comment by jdoleary** [comment]
We *may* to leave the "you can end turn before teammate places character".  The end turn logic is very complicated with lots of hidden potential issues.  It's been designed so that the game can never get stuck.  We don't want someone to load into a game with 2 players and one is absent and them not be able to progress for example.  We have to be very very careful here.  (We also have to consider hotseat).  This portion of this issue might best be left alone.

But we can add special logic to resurrect to set endedTurn to false if the unit is a player's unit.  Just check the unitType is PlayerControlled and then iterate the array of players to find the matching unit.

**Comment by jdoleary** [comment]
@SoulMuncher  Just saw this one in discord, despite my earlier comment, it should be simple and safe to set `endedTurn` to false after a unit is resurrected inside the resurrect spells or in a Unit.ts function that all 3 resurrect cards use.

**Comment by SoulMuncher** [comment]
> @jdoleary set `endedTurn` to false after a unit is resurrected

That's the plan! Should be a good fix for the resurrect one. I may not touch the spawn issue yet, for the reasons you listed. Will have to see how deep it goes and do some quick testing with hotseat and stuff.

**Comment by SoulMuncher** [comment]
Going to split the turn one off into a new issue and repurpose this one into the res issue
