### ISSUE TITLE
MultiColorReplaceFilter Issue

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#33]
![BloodGolemSprite](https://github.com/jdoleary/Spellmasons/assets/68413161/05aa5dca-d45f-410a-9de9-995b190e95b8)

I found some blood golem enemies using a broken sprite in Lava World when playing through the game normally in dev tab.

0/2 repro attempts, cause unknown.

**Comment by SoulMuncher** [comment]
> What browser are you using? Electronjs runs on chromium and so the Steam version is essentially running on chrome. I've seen this issue on Firefox but not on chrome

Microsoft Edge (I know, yuck)

**Comment by jdoleary** [comment]
lol well Edge is still chromium underneath so I wouldn't expect that.  Let's keep an eye on it and see if we can determine what makes it reproducable

**Comment by jdoleary** [comment]
> Only seems to affect higher level versions of units (i.e. blood golem but not default golem)
Only the blood golum has a MultiColorReplaceFilter on it.  This is due to the MultiColorReplaceFilter not functioning as it usually does.  So I know __what's__ happening but not why.

> Two sprites overlap, one is always the default sprite (i.e. can't mix blood and ghost archer, only blood+default or ghost+default)
I'm not sure what you mean by this.

**Comment by SoulMuncher** [comment]
> I'm not sure what you mean by this.

Any tier 2+ unit can have a bugged sprite, including the blood archer and ghost archer. The bugged sprite will be a mix of the upgraded unit's sprite, and the default sprite of that unit (blood archer + archer OR ghost archer + archer).

I was saying that, as you might expect, it will never be a mix between two upgraded units, such as a blood archer + ghost archer combination.

**Comment by jdoleary** [comment]
Ah yes okay, this makes sense.  So some background, the way the multicolor replace filter works is it swaps out colors given a certain tolerance (distance from current pixel color to the source color).  I'm using this filter (shader) so I don't have to make a ton of new sprites when all that's changed is their color.  But as you've noticed this issue crops up every once in a while.

I'd say this is low priority since it's so inconsistent, but let's both of us take any opportunity that we see it happen to try to investigate and determine root cause.

One thing I have noticed is that overlapping sprites (like the invulnerability circle on the "plus" levels after the deathmason) can cause the shader not to work, so maybe there's a condition where the sprite's color is changed for some reason or maybe the tolerance just needs to be increased.

It'd also be useful to note if this is happening to a particular unit more than others or if it happens across the board to all MultiColodReplacedFilter'd units at the same time.

**Comment by jdoleary** [comment]
Okay this is more of a problem than I thought then.  I'll try to reproduce on edge

**Comment by jdoleary** [comment]
@SoulMuncher This may be resolved by 8789a98.  Please let me know if you see this again

**Comment by SoulMuncher** [comment]
I haven't seen this bug happen since your commit. If it doesn't show up by 1.26 milestone, I think we can close it. Nice fix! 😄

**Comment by jdoleary** [comment]
Awesome!  Yeah I didn't even notice that I had been exporting in png8, I must've changed it accidentally and then noticed while looking at a diff.
I'll close it!
