### ISSUE TITLE
deathmason boss stops doing things if bitten by mana-vampire.

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#350]
> SneakyMinion
> OP
>  — Today at 7:20 AM
> he just stops moving/casting spells or doing anything the moment he gets bitten even just once.
> 
> so despite still having 140-180 mana, seems to just give up on life (to be fair, I give up the moment a mana-vampire bites me too; instant rage-quit)

**Comment by jdoleary** [comment]
Maybe we should change mana vampire to reduce `mana` and not `manaMax`.  I've heard frustrations about this from other players too unrelated to the deathmason - just specifically about the design of the mana vampire. 
Thoughts @SoulMuncher ?

**Comment by SoulMuncher** [comment]
> @jdoleary
Maybe we should change mana vampire to reduce `mana` and not `manaMax`. I've heard frustrations about this from other players too unrelated to the deathmason - just specifically about the design of the mana vampire. Thoughts @SoulMuncher ?

Changing it to something like that sounds like a good idea. If we make it simply drain mana, it'll need some extra logic to handle players, since they'll just regen at the start of their turn.

We could also do some other fun stuff like:
- Actually steals the mana, and has some extra effect related to the mana it carries:
- - Regains health equal to the amount stolen (very vampirey, still impactful vs players, I like this one)
- - Dispenses all mana back to its killer (could work on another unit, has some fun implications)
- - Consumes some mana each turn to heal itself (fun implications with send-mana and other mana manipulation strategies, doesn't leave as much mana sitting on the unit)
- Deals extra damage equal to the mana it burns from its target
- Applies some negative modifier to mana/mana regen/mana max/mana cost that disappears at the end of level or over time
- Applies some modifier that prevents or penalizes the usage of mana for a turn

**Comment by jdoleary** [comment]
Good point.  I want to fix this but maybe we leave it for 1.28.  For now what do you think about reducing the deathmason's cost to cast so at least a single mana vampire doesn't render the deathmason useless?

**Comment by SoulMuncher** [comment]
> Good point. I want to fix this but maybe we leave it for 1.28. For now what do you think about reducing the deathmason's cost to cast so at least a single mana vampire doesn't render the deathmason useless?

Sounds good to me 😄
