### ISSUE TITLE
New Unit: Goru

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#386]

**Comment by SoulMuncher** [comment]
@jdoleary 

## Goru Ideas:
- Should require some strategy/thought, can't be brute forced with damage or summon spam.
- Should also be a real threat, not a meat shield to chip away at
- Should have unique mechanics that allow players to use spells in new/creative ways that wouldn't usually come into play in regular levels.
- Should have counters and counterplay

.

- **Undying modifier** - This creates a resistance to most of the usual anti-boss strategies, such as rend/bleed and most curses, by giving the boss 'resets'. Ensures the fight lasts a few turns minimum. I also imagine them emitting some kind of curse/summon explosion with each respawn
- **Corpse Interactions** - Gives the boss anti-summon potential, which is good because we want players to interact with bosses instead of brute forcing with damage or summon spam. Corpse mechanics should have some unique counterplay, such as using Merge and Bone Shrapnel to limit corpse count.
  - **Explosion** - AoE, which is unique and anti-summon.
  - **Consumption** - Would heal the boss or similar
  - **Resurrect** - Gives Goru summons (but with counterplay)
- **Curses + Contaminate** - Makes the Goru individually threatening, which is important if you can limit their summoning by controlling corpses, positioning becomes much more important, and unique because not many units apply curses. I imagine Poison/Debilitate/Slow would be good options. This would also put a timer on the fight, which is important since the Goru won't be relying on summons to create that rising threat. I also imagine he has low range + teleports? This will depend on how everything else feels.

.

These ideas are more "diseased mummy" themed than "magic ghost" themed I guess 🤔 The Goru seems much more ethereal now that I'm looking at it again.

**Comment by jdoleary** [comment]
I like these ideas!  We could also give him "aura-like" behavior where any units within a radius of him take damage on his turn.  This could be done without changing any engine code and would still be anti-summon.

I think "magic ghost" still works well with these ideas

**Comment by SoulMuncher** [comment]
> I like these ideas! We could also give him "aura-like" behavior where any units within a radius of him take damage on his turn. This could be done without changing any engine code and would still be anti-summon.

Definitely! I like this a lot.
