### ISSUE TITLE
AI State Machine Refactor

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#388]

**Comment by SoulMuncher** [comment]
**IMPORTANT:**
Predictions are not simulated out the same way they would actually occur in real time. Things like PlanningView and OnDrawSelected tend to find targets based on the current game state, not factoring in the allies that would act before enemies, effects like bloat that can change the outcome of combat, and damage modifiers like debilitate and fortify, which are not considered while incrementing a unit's next turn damage.

**Comment by SoulMuncher** [comment]
Related Issues:
(Add more as needed)

#55 
#214 
#408 
#409

**Comment by jdoleary** [comment]
Since we're transitioning to stability focus and away from new features for the moment I'm going to close this as not planned.

**Comment by SoulMuncher** [comment]
https://github.com/jdoleary/Spellmasons/pull/868#issuecomment-2229361160


Ideally, prediction would always show "game-state directly after cast", and everything else would be in some generic incoming healing/damage overlay. Doing this reliably would require a huge refactor of the prediction/smart targeting code, and I would rather it not exist than be unreliable.

As an example: Smart Targeting runs all ai units at the same time, instead of having an ally turn and then an enemy turn. This means that those units turnStart/End events don't run in the correct order, which is very problematic when introducing health regen, poison, etc. Smart Targeting also doesn't use Unit.takeDamage() or Unit.die() either, so it skips onDamage/onDeath events, including modifiers like debilitate, fortify, bloat explosions, etc.
