### ISSUE TITLE
New Spell: Execute

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#471]
A damage spell that insta-kills a unit under a certain health threshold. Stacks increase the threshold
This may need some work to feel different from "Bleed"

**Comment by SoulMuncher** [comment]
Could be interesting if it was rethemed to sort've "exile" the enemy, essentially just deleting them or removing them from the game without triggering any onDeath events? Might be tricky with exp and other universal on death stuff

**Comment by jdoleary** [comment]
Before you make this one I'd like to discuss how it'll feel different from bleed.  I'm not sure I like the no on-death events.  I think that could be confusing.  What if it's a range + health threshold combo (like shove).  So if they're below 50% health and within "melee" range you can execute them.  I kinda like that

**Comment by jdoleary** [comment]
I've had more time to think about it and I'm sold on
>  if they're below 50% health and within "melee" range you can execute them. I kinda like that
This will be one of the melee type spells like shove where you have to be right next to an enemy to use it.
This is interesting because it means you have to go towards danger to take advantage of it.
But it has the powerful benefit that you can execute ANYONE at or under 50% health which is a lot better than bleed
