### ISSUE TITLE
New Spell: Polymorph

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#474]
Changes a unit into another random unit

Since I love for Spellmasons to suprise people, if players are chaotic enough to self-cast polymorph I think they should be allowed to use the abilities of the unit that they poly into. Maybe even give them hidden stat upgrades (like upgrading damage). This would be a very rewarding suprise. It would also have to disable or remove their regular spells (until they purify to unpolymorph)

Basically the idea is to pleasantly suprise. If you so choose to turn yourself or your ally spellmason into an archer, I'd expect you to then only have arrow spells and be able to play a "hidden game" of Spellmasons as an Archer instead of a wizard. If you poly into a golem, you'll only have a "bite" attack. Yes, super limiting but therein lies the pleasant suprise. It's the natural consequence of polymorphing yourself and I think players will love it.

Also it being reversable via purify will make the mistake more hilarious and forgivable in multiplayer (provided you have it)

**Comment by SoulMuncher** [comment]
We should consider timelines, and whether or not this spell is worth the work it would require implementing. We may need to cut it, and if not, it should be considered in the #388

**Comment by jdoleary** [comment]
New idea for simplifying this: 
If you cast on a player:
It changes your image (animation) to a random unit and makes it so that that same unit won't target you.  So if you get polymorphed into a golem, no enemy golems will attack you.  Nothing else changes, just your appearance and your "herd-immunity"
But when it's cast on an NPC they actually change into that unit.
