### ISSUE TITLE
New Spell: Soul Shard

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#478]
The caster splits a piece of their soul into the target. When the target takes damage so does the caster, but if the caster dies, they will reincarnate in the body of the shard-haver

This should be do-able with modifiers

**Comment by SoulMuncher** [comment]
Is this functionally a polymorph, or does the player turn into a Spellmason again?

**Comment by jdoleary** [comment]
The shard-haver is deleted and the Spellmason respawns in their location as the Spellmason

**Comment by jdoleary** [comment]
Example scenario:
- Spellmasons casts spell shard on 2 golems.
- Golem 1 takes 30 damage (and thus that damage is reflected onto the Spellmason)  _(question: should the damage be duplicated or ONLY apply to the spellmason - either could be interesting, what do you think)_
- Spellmason takes direct damage and dies
- Spellmason is instantly reincarnated in the place of one (closest? random?) of the golems and the golem instantly dies (dies rather than deleted incase players soul shard each other we don't want to be deleting spellmasons)

**Comment by jdoleary** [comment]
Also for an effect to show which units are soul sharded, let's have a crystal float above their heads (like in the Sims). ( I'll replace the image later ) for now, just get any small image floating above their heads as a subsprite (like how spell effects like debilitate are subsprites but this one is just never removed).  Make sure it works with save/load please
