### ISSUE TITLE
Bug: Stamina resets if you move while casting in multiplayer

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#547]
> HawkC120
OP
 — Today at 1:07 AM
When casting a spell, you can move- this consumes your stamina. But when the animation finishes, it resets your stamina to what it was before the spell cast. Allowing you to move again.

Multiplayer only

**Comment by SoulMuncher** [comment]
Is this because move resolves instantly and the spell syncs all unit stamina values after?

We could give player clients ownership of their stamina value, but then there would be an issue any time the spell should've changed the stamina amount and we don't respect that change (i.e. a stamina potion gets pushed into a player or something).

Making player movement queued up is off the table... This is a tricky one.

**Comment by jdoleary** [comment]
Well the spell still triggers on all the client too so I think giving the client ownership of their stamina would work.

**Comment by SoulMuncher** [comment]
@jdoleary I haven't been able to repro this today
