### ISSUE TITLE
Bug: Purify doesn't revert 36 stacks of slow

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#574]
ae?
https://discord.com/channels/1032294536640200766/1032294537235812404/1221191388792881314

**Comment by SoulMuncher** [comment]
I attempted to repro this in singleplayer and couldn't. I did not try multiplayer. Even up to >1,000,000 stacks of slow, purify and the between-level-reset restore staminaMax correctly.

In the linked discord conversation, there's a screenshot of what looks like the stat-point-allocation screen where the player has near 0 max stamina, but I'm not sure how the player managed to end up in that situation *before* allocating stats, since it shouldn't carry between levels.
