### ISSUE TITLE
Arrow Collision

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#63]
Multiple exploding arrows shot from [(targetting spells) + Exploding Arrow] will repeatedly collide with the first enemy, even after that enemy has been killed. This leads to incorrect predictions.

**Comment by SoulMuncher** [comment]
Similar issue with arrow predictions:

- Have two targets near each other, and lined up in such a way that you could hit them both with one line of arrows.
- Apply bloat to the first target
- Make sure second target has > 40 hp
- Queue up arrows
- Notice how the second target is not predicted to be hit by any arrows, as the prediction thinks the bloat will push them away first
- Shoot a bunch of arrows
- Notice how the second target gets hit by an additional arrow mid-bloat-push

**Comment by jdoleary** [comment]
Hmm this is indeed tricky.  Originally I had it so one arrow didn't fire until the last arrow had hit it's target, which didn't incur these misprediction issues, however, people who play arrow builds tend to launch TONS of arrows and it took forever for the spell to finish, so I changed it so that arrows fire faster and faster (which feels and looks really cool IMO) but it introduced these sync complexities...  I'd like to keep the faster arrows but it might be complicated to resolve the prediction issues

**Comment by jdoleary** [comment]
One way to fix this might be to separate the visual arrows from the collision logic.  So for example:
We could revert it to where the arrows only fire one at a time and don't send the next arrow until the first is complete, then when there's a ton of arrows being shot, we could just speed up the arrow travel speed until it's near instantaneous and/or leave the visual arrow projectiles separate from the collision calculation.  I'm not sure how this will turn out in practice, but it's probably best to ensure that the arrow predictions are correct over it looking visually appealing

**Comment by SoulMuncher** [comment]
Thanks for finishing this one up! Interested to see what you meant with the additional invoke function wrapping. 😄

**Comment by SoulMuncher** [comment]
going as part of the prediction refactor

**Comment by jdoleary** [comment]
I'll take this one, I've got a new idea for how to make it work

**Comment by jdoleary** [comment]
Note to self: setTimeouts will have to be triggered via the millis that pass in deltaTime for gameloops in headless to be fully consistent with prediction
