### ISSUE TITLE
Balance Clone + Merge

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#724]
A level 4 player was able to make an infinite army of himself
https://discord.com/channels/1032294536640200766/1032294537235812404/1239990667426398218

**Comment by SoulMuncher** [comment]
Kind've random thought, but why am I allowed to cast I cast [freeze + arrow + freeze] but not [freeze + arrow] + [freeze]?
Shouldn't freeze go on cooldown once arrow is added after it, since that one cast of freeze is complete/quantity set?

I think this would also be a really really good solution for not just the clone/merge combo, but clone in general.

**Comment by jdoleary** [comment]
That's a good point.  I wonder how simple this would be to implement.  I'd say if it's easy then yes let's and if not, no

**Comment by SoulMuncher** [comment]
Idea: #759

**Comment by jdoleary** [comment]
Fixed in #182
