### ISSUE TITLE
Splitting corpses with "Primed Corpse 1" on them bugs the particles

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#859]
https://discord.com/channels/1032294536640200766/1260691387289174026/1260691387289174026

**Comment by SoulMuncher** [comment]
This issue is present on current steam version b7e824233087a9a4ced6d2e48077549da66191e8
but I believe it was fixed with the following commit ea147a4feba8a8c4973261632777fc9b8763433f

1.39.1 Repro:
- New game
- Skip to ghost biome
- Kill all enemies
- Super me (for Split spell)
- End turn, Goru Spawns
- End turn, Goru Primes corpses
- Attempt to Split a corpse, but notice how the vfx multiplies in prediction
