### ISSUE TITLE
Manasteal Nerf

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#93]
I hope I don't need to elaborate on this one

**Comment by jdoleary** [comment]
I want to be careful with this, I do want it to be possible for players to get absurd amounts of mana if they are clever enough.  A previous strat, was Last Will, but that resulted in near infinite mana because it used to stack and there was no Cursed Mana Potion like there is now.
We can surely balance it, but we must maintain a way for clever players to get powerful enough that they can do huge combos.

**Comment by jdoleary** [comment]
> scojbo — Today at 6:48 PM
> Might I say: the problem with late-game map-wiping spells is largely due to mana-steal being incredibly OP late-game and enabling you way beyond what you could otherwise do.
>  Since you're addressing late-game anyways, perhaps cap bonus mana or make mana-steal a combo spell that first requires mana burnto unlock or nerf mana-steal some other way? 
>
