### ISSUE TITLE
Update name from UUID before placing Spellmason

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#94]
May be the root cause of some issues involving players losing control of their character in multiplayer after reconnecting.

**Comment by jdoleary** [comment]
Some background:
When I designed WebsocketPie (the networking backend), I had it set the clientId to 'solomodeid' (sp?) when playing in singleplayer and giving them a UUID for multiplayer.  In hindsight this was a mistake.  it means that if you play multiplayer, switch to singleplayer and then come back to multiplayer you'll have a different UUID.  This is what causes a lot of that "rejoining an old save game and starting as a new character".  Ideally WebsocketPie would just assign a single UUID and store it in localStorage (but I think I might need cookie consent for that? not sure - GDPR).

As a temporary bandaid, I made it so if you join a game with the same name as a player that isn't currently controlled by a client it sets you to that player.  WebsocketPie allows you to send your clientId as a queryString when you connect, so the ideal way to do this would be by having only one clientid ever.  Or maybe allowing it to change the client id so that it will always be your name if you choose one.

Anyway, that's the history.  It's definitely not ideal at the moment, and I think most of the work actually needs to happen in websocketpie (https://github.com/jdoleary/WebsocketPie). Looking forward to hearing your thoughts.

**Comment by SoulMuncher** [comment]
@jdoleary 
> I made it so if you join a game with the same name as a player...

Sometimes the player name is _saved as the UUID_, as seen in the top left turn-tracker and in the pre-game lobby. I'm now guessing that's not intentional?

**Comment by jdoleary** [comment]
Related: #147

**Comment by jdoleary** [comment]
This may be fixed in b090023
