### ISSUE TITLE
Last will potions not spawning sometimes

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#968]
https://discord.com/channels/1032294536640200766/1271898421615136809/1271995786418327582

**Comment by jdoleary** [comment]
@SoulMuncher could this be fixed with your new "find spawn point" function?

**Comment by SoulMuncher** [comment]
@jdoleary 
Yes. They'll need some more generalization before being used elsewhere though.

Take in a `center: vec2` and `maxRadius: number` instead of a unit, having an optional `minRadius`, maybe `allowSpawnInLiquid: boolean`, stuff like that. Different effects may want slight modifications or have different "validity" checks regarding liquid, entity overlap, etc.

The ones I wrote were done super quick to get the individual runes working
