### ISSUE TITLE
Urn explosion radius on select

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#97]
You should be able to see the explosion radius of an urn when you select it.

**Comment by SoulMuncher** [comment]
@jdoleary
I've more-or-less figured this one out, but I think there needs to be a broader discussion and possibly refactor on doodads first:

There are points in the codebase where doodads are doodads and points in the codebase where doodads are a subtype of units. Currently, Doodads return as a unit from Unit.isUnit(), but they do not return as doodads in isDoodad() because their primary "type" is unit.

Which way do we go with it, are they units or not units? It seems like both ideas were tried out and the old one was not entirely cleaned up. To me it makes sense that a Doodad is a unit, at least for the current doodads (urns), and I think that will be easier to work with and give future doodads more potential, but I also think it depends on what future things you would consider a doodad.

**Comment by jdoleary** [comment]
The non-unit doodads are left-over and should be cleaned up.  Long ago I tried to make them they're own thing but it was a problem because there were TONS of places that then needed special checks to include the targetedDoodads so I just unhooked it and didn't clean it up.
Current doodads (urns) are units because they have health and can be killed.  The main difference is that they don't do anything on their turn (no action()) and their faction doesn't matter.   And then I needed to add special logic to prevent AI from targeting them... not a perfect solution to be sure. I'm open to options for improving it.
If I had more foresight I could've used composition better here.  Pickups and units share x,y and physics, units and doodads share health and death.
There should probably just be a targeted array instead of targetedUnits and targetedPickups and then just check what they are when iterating. 

Not sure how much of that history is relevant but I think I answered your question.
